name: 新聞自動巡邏

on:
  schedule:
    - cron: '6,27,48 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # 必須開啟寫入權限，才能存儲新聞紀錄
    permissions:
      contents: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests feedparser

      - name: Run Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Commit and Push if records updated
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add sent_links.txt || exit 0
          git commit -m "Update sent news history [skip ci]" || exit 0
          git push
